language: cpp
compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic

install:
  - sudo apt update
  - sudo apt install libgtest-dev
  - (cd /usr/src/gtest && sudo `which cmake` .)
  - sudo make -C /usr/src/gtest
  - sudo ln -s /usr/src/gtest/libgtest.a /usr/lib/libgtest.a
  - sudo ln -s /usr/src/gtest/libgtest_main.a /usr/lib/libgtest_main.a

script:
  - mkdir build
  - cd build
  - cmake ../ttl
  - make -j2
  - ./ttl-test-cxx11
  - ./ttl-test-cxx14
  - ./ttl-test-cxx17